name:                sniper
version:             0.1.0.0
github:              "lumapat/sniper"
license:             MIT
author:              "Miguel Lumapat"
maintainer:          "wzzch@naver.com"
copyright:           "2020 Miguel Lumapat"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lumapat/sniper#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  sniper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - servant
    - servant-server
    - sniper
    - wai
    - warp

tests:
  sniper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sniper
